### ISSUE TITLE
Invoked widgets can not have dynamic w-ids

### ISSUE THREAD

**Issue by jackhorton** [marko-js/marko-widgets#51] opened 2015-07-01 17:14 UTC
`<invoke>`ing a widget with a w-id (as in #46) only works when the w-id is static. Widgets invoked via taglib can have dynamic IDs, however, so that `<widget w-id="${widgetName}" />` works, but `<invoke function="..." w-id="${widgetName}" />` does not. Instead, it gives an entirely new w-id.

**Comment by patrick-steele-idem** [comment] 2015-08-10 22:07
I'm not able to reproduce. I added a test case that I thought would reproduce the problem and the test case is passing: https://github.com/marko-js/marko-widgets/commit/0e0b85c4791ccc81c2d49b8eb3a84a79a6c6ed09

I suspect that maybe this was fixed by another change. I'm going to go ahead and close this issue, but please let me know if you still see this issue. Thanks.

**Closed by patrick-steele-idem** 2015-08-10 22:07 UTC
