### ISSUE TITLE
Cannot find module from "/$/marko-widgets/lib"

### ISSUE THREAD

**Issue by rtalwar26** [marko-js/marko-widgets#136] opened 2016-05-20 13:17 UTC
Hi , Iam facing this issue when I try to bind `index.js` file via `w-bind` when using marko-widgets

The error is

```javascript
Uncaught Error: Cannot find module "/demo$1.0.0/backend/v2/components/pmr-main-view/index" from "/$/marko-widgets/lib"
```

I think something is wrong with the directory structure because it is prefixing the node project's name `demo` before requiring any module.
I am running the app from the projects directory 

```shell
node backend/app.js
```
 I have uploaded the [demo project here] (https://github.com/rtalwar26/marko-widget-demo).

**Comment by rtalwar26** [comment] 2016-05-23 16:56
Guess this was occurring through some outdated dependency in node_modules, i cleared them and updated to latest and the error is gone. Also marko, marko-widgets and lasso were latest when the build broke.

**Comment by patrick-steele-idem** [comment] 2016-05-23 21:43
Not sure what happened. Since I'm not able to reproduce I am going to go ahead and close this issue. Please let me know if you see the problem again. Thanks.

**Closed by patrick-steele-idem** 2016-05-23 21:43 UTC
